repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_providers_lock
        args:
        - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.3.347
    hooks:
      - id: checkov
        args: [--quiet]
