languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "A tech blog"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
   name = "Shirwa Hersi"
  # image = "img/author.jpg"
  # headline = "I'm only human"
  # bio = "A little bit about you"
   links = [
     { github = "https://github.com/shirwahersi" },
     { linkedin = "https://linkedin.com/in/shirwahersi" },
   ]
